project:
  type: website
  output-dir: docs

website:
  site-url: "https://felixanalytix.com"
  title: "Felix Analytix"
  search: false
  navbar:
    right:
      - icon: youtube
        text: Youtube
        href: https://youtube.com/@FelixAnalytix
      - icon: medium
        text: Blog
        href: https://felixanalytix.medium.com/
      - icon: twitter
        href: https://twitter.com/felixanalytix
      - icon: instagram
        href: https://instagram.com/felixanalytix

format:
  html:
    theme: zephyr
    css: styles.css
